# Generated by Django 3.2.13 on 2022-06-29 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SVNP', '0002_alter_file_file_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='project_data/SVNP/', verbose_name='Загрузите файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_version',
            field=models.CharField(max_length=3, verbose_name='Версия файла'),
        ),
        migrations.AlterField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
